# [".oh-my-zsh"]
# type = "git-repo"
# url = "https://github.com/ohmyzsh/ohmyzsh.git"
# # exact = false
# # stripComponents = 1
# refreshPeriod = "168h"

# [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
# # exact = false
# # stripComponents = 1
# refreshPeriod = "168h"


# [".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-autosuggestions.git"
# # exact = false
# # stripComponents = 1
# refreshPeriod = "168h"

# [".config/shell/plugins/dircolors-solarized"]
# type = "git-repo"
# url = "https://github.com/seebi/dircolors-solarized.git"
# # exact = false
# # stripComponents = 1
# refreshPeriod = "168h"

# [".nvm"]
# type = "git-repo"
# url = "https://github.com/nvm-sh/nvm.git"
# # exact = false
# # stripComponents = 1
# refreshPeriod = "168h"
