# yaml-language-server: $schema=https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/bundled/config/document.vscode.json
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
metadata:
  Microsoft.DSC:
    securityContext: Elevated
resources:
  - name: AppsDarkMode
    type: Microsoft.Windows/Registry
    properties:
      keyPath: HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
      valueName: AppsUseLightTheme
      valueData:
        DWord: 0

  - name: SystemUsesLightTheme
    type: Microsoft.Windows/Registry
    properties:
      keyPath: HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize
      valueName: SystemUsesLightTheme
      valueData:
        DWord: 0
